project:
  type: book

book:
  title: "TsA in Finance - Group project"
  subtitle: "Swiss National Bank Policy Rates and Inflation Dynamics"
  author: "Daniel Huber / Dongyuan Gao"
  date: "2025-05-20"
  chapters:
    - index.qmd
    - sections/Chapter_1_to_5.qmd
    - sections/R_analysis.qmd
    - sections/Chapter_6_to_8.qmd

format:
  html:
    toc: true
    theme: flatly
    page-layout: full
  pdf:
    toc: true
    number-sections: true
    documentclass: report
    geometry: top=2.5cm, bottom=1.5cm, left=2cm, right=2cm
    mainfont: Arial

execute:
  echo: true
  warning: false
  message: false
