---
editor: 
  markdown: 
    wrap: 72
---

# Findings, limitations and discussion

## Key findings

1.  **Linear Regression model with Lag Effects shows weak relations**\
    A basic linear regression showed no significant relationship between
    policy rates and inflation (p \> 0.05; R² ≈ 0.004). When including
    lags of up to 12 months, lag 1 and lag 10 were statistically
    significant. While in this context a lag of 10 months might be
    feasible, we still have doubts. Overall explanatory power was low
    (adjusted R² ≈ 0.02). It suggests only weak evidence of delayed
    effects.

2.  **Linear Regression model with SNB events shows evidence of one
    event in 2022**\
    After treating major SNB policy changes as events, October 2022 had
    a statistically significant effect on inflation (p close to 0). This
    suggests that a major policy change (from negative to positive rates
    in 2022) might have had an effect on inflation. However, overall
    explanatory power was still very low (R² ≈ 0.04).

3.  **Granger Causality (VAR Model) but not deterministic**\
    The Granger causality test showed that policy rates Granger-cause
    inflation (p ≈ 0.024). It suggested that past policy rate changes
    help predict inflation. But remember, no causality can be
    determined. On the other hand, inflation did not Granger-cause
    policy rates (p ≈0.29). Either the SNB really acts independently of
    recent inflation trends, which is against theory, or we just did not
    find an appropriate model to prove that SNB policy reacts to
    inflation rates.

4.  **ARIMA forecasting suggests reverting behavior**\
    An ARIMA(5,1,0) model on inflation rates shows significant
    auto-regressive effects of lags 1-5 on inflation rates. The negative
    estimates in all lags suggest an auto-reverting effect: a rise in
    inflation is followed by an decrease. We have also done forecast,
    but no significant changes of inflation were predicted.

## Limitations

-   **Limited Prediction Power**: Most models (especially linear
    regression) show very low R² values, indicating weak predictive
    power.

-   **Only two Variables**: The models only consider two variables:
    policy rate and core inflation. Other factors like global energy
    prices, the pandemic or global trade conflicts were not included.

Despite these limitations, the analysis contributes to understanding how
SNB policy rates and inflation interact. It offers a foundation for more
complex modeling in future studies.

```{=latex}
\newpage
```

## Discussion

Are the results from linear regression (SNB event), ARIMA (5,1,0) and
Granger causality test consistent?

**Linear regression**: There is an effect of a major SNB change in
policy rate, but the model only explains a small portion of variance in
inflation rates.

**ARIMA**: It uses past values of inflation to forecast future inflation
so it is a univariate model, not taking into account other variables
(e.g., policy events).

**Granger Causality Test**: Multivariate test: It checks if variables
(like our events or interest rate changes) help to explain each other
better then they are explained by themselves.

**The results are actually consistent, without contradiction**:

Based on the linear regression model a major change in SNB policy rates
explains inflation rates variance, but only a very small portion of it.
ARIMA shows an auto-regressive reverting effect, inflation can be in
parts be explained by itself. But , without further checking the quality
of the ARIMA model, the respective forecast based on this model was not
convincing. Finally, the Granger causality test shows an effect of
policy rates on inflation, suggesting that it can help explaining
inflation. The other way round, there is no effect of inflation rates on
policy rate.

So, our analysis **suggests an effect of SNB policy rates on
inflation**, which is itself auto-correlated. But all relationships and
model are rather to very weak. Meaning our results were **consistent**
without contradiction but only show **weak effects**.

# Conclusion

Our team analyzed the relationship between SNB policy rates and
inflation rate in Switzerland. We applied several time series models for
the analysis.

Weak connections between the two variables were found, lacking strong
correlation or deterministic evidence.

However, some non-deterministic effects were observed:

-   Granger causality indicates that past policy rate changes have some
    predictive value for inflation.

-   Event-based regression suggests a mild relation between a major
    change in SNB policy on inflation.

-   ARIMA suggests an auto-regressive and reverting behavior of the
    inflation rates.

The findings suggest that inflation in Switzerland could be influenced
by a broader set of factors, including monetary policy, but not limited
to it.

Future research could expand on this work by including more variables,
testing other models, analyzing specific events' effect on inflation
rate, and their relationship with policy decisions.

# Bibliography

\[Infl00\] *Inflation rates in Switzerland*. URL:
https://www.worlddata.info/europe/switzerland/inflation-rates.php -
retrieved: 2025-05-18. —Worlddata.info

\[Inte00\] Interest rates and threshold factor. URL:
https://data.snb.ch/en/topics/snb/cube/snbgwdzid - retrieved:
2025-05-14. — Interest rates and threshold factor

\[Mark23\] Marking 30 years of the Taylor rule \| Stanford Institute for
Economic Policy Research (SIEPR). URL:
https://siepr.stanford.edu/news/marking-30-years-taylor-rule -
retrieved: 2025-05-14

\[Schi00\] SCHINDLER, JOHN: The Swiss National Bank’s Three-month Libor
Target (2000)

\[Snbd00\] SNB data portal. URL:
https://data.snb.ch/en/topics/snb/cube/snbgwdzid - retrieved:
2025-05-15. — SNB data portal
