---
editor: 
  markdown: 
    wrap: 72
---

# Motivation and Objective

## Project Objectives

The project aims to

-   investigate the dynamic relationship between SNB’s policy interest
    rates and Swiss core inflation.

-   determine if there is causality between these two variables.

-   analyze the impact and timing of policy rate adjustments on
    inflation.

-   help team members learn about Time Series Analysis by doing,
    including models, theory, tools that we explored in class

## Motivation

Personal/team motivation:

We share a strong academic interest in exploring the world of financial
analysis and were motivated by the opportunity to apply our skills to a
real-world scenario with practical relevance in the Swiss context. This
project also aligns with our professional aspirations, for example,
finance, market research, and trading. That makes the project both
intellectually engaging and career-relevant.

Real-world relevance: In today’s volatile economic landscape, it is
beneficial for individuals and institutions to understand inflation
dynamics. Such insights can contribute to better financial or policy
decisions. It is relevant for policymakers, investors, researchers and
private individuals.

## Research Questions

-   Does SNB policy rate significantly influence core inflation, Or vice
    versa?

-   For policy rate and core inflation, can changes in one predict the
    other?.

-   How quickly and how strongly do core inflation rates respond to
    policy changes?

-   Exploring any extra findings In the relationship between inflation
    rates and the SNB's policy Interest rates, during the project
    implementation.

# Theory, literature and methodology

To answer our research questions, we first needed to clarify what the
basis for modern monetary policy is. Why do central banks raise and
lower interest rates according to inflation? For that, a benchmark for
monetary policy theory is Taylor’s rule, in which he defined the formula
for the targeted rate of central banks. “Put simply, the Taylor rule
says that the Federal Reserve should raise the interest rate when
inflation increases and lower the interest rate when gross domestic
product (GDP) declines. The desired interest rate is one-and-a-half
times the inflation rate, plus one-half times the gap between GDP and
its potential, plus one.” \[Mark23\]

Then the next clarification is: how does Switzerland evaluate and
implement monetary policy to foster economic prosperity? After trying
out some datasets, we discovered the following statements: “Since the
beginning of 2000, the Swiss National Bank (SNB) has used a range for
the three-month Swiss franc Libor as its announced target for monetary
policy.” “Before 2000, the Swiss National Bank officially targeted
monetary aggregates, using a medium-term target for the
seasonally-adjusted monetary base.”\[Schi00\]

Then for the analysis, we have adopted the theory and practice what we
have learned in TSA classes. For example, VAR modeling, stationarity
testing, Granger causality, lag-lead effect, and ARIMA.

# Data selection process

First, after some research, we started the analysis with a dataset from
SNB, “Interest rates and threshold factor” \[Inte00a\], afterwards is
called Dataset 1. It includes policy rate (for a short period), interest
rate on sight deposits above threshold, special rate, SARON fix etc. For
inflation data, we used core inflation, trimmed mean from “Consumer
prices – SNB and SFSO core inflation rates” \[Cons00b\].

In Dataset 1, the threshold is more suitable to use as the interest rate
policy target. However, since threshold data is not available before
2009, we used the special rate for earlier years. From 13 June 2019, the
special rate was based on the current SNB policy rate plus a surcharge
of 50 basis points.

Additionally, we determined that the SARON fix rate is the market
reaction to the policy target, so it shouldn’t be used as the policy
rate to be analyzed.

The trial analysis has been successful; we were able to draw some
findings and conclusions applying ARIMA, VAR, and linear regression.
However, we were not fully satisfied with the different rate types. It
was puzzling that we had to convert and “compromise” to the complicated
data structure. Therefore, we continued our research and found a second
Dataset (referred to as Dataset 2), which contains only two types of
official interest rate data. This made it more consistent and more
suitable to use as the policy rate.

In this Dataset 2, “From 13 June 2019, the SNB policy rate is applied.
From 3 January 2000 until 13 June 2019, the SNB set a target range for
the three-month Swiss franc Libor” \[Snbd00\].

With it, we’ve also done a VAR to check causality between policy
rate/target to inflation, or vice versa. As with Dataset 1, no causality
was proven, and in Dataset 2, one direction causality was proven, it
shows that the dats sets actually produced different results.

In the end, we chose Dataset 2 for the final analysis. Still, the data
selection process was an important learning experience and worth sharing
with readers.

# Team collaboration and tool set

## Team organization and meetings

Team structure: For our team of 2, we both shared responsibility for all
aspects of the project; however, with a focus on different aspects. For
example, Daniel presented the initial idea, Dongyuan focused more on
methodology and research, Daniel focused more on coding diverse models,
and Dongyuan dived into finding more data options during the project. We
reached team consensus through weekly meetings and follow-ups. The tasks
were also interest-based according to both team members. Meeting
schedule: weekly meetings were set up on Monday/Tuesday at 14:00, and
frequent follow-ups took place.

## Collaborative tools

### Brainstorming and ideation:

Miro Board - Initial concept visualization, real-time collaboration on
ideas and analysis structure, organizing literature and conceptual
mapping

### Task Distribution and Project Management

Excel - Task assignment tracking, deadlines and progress monitoring,
visualization of milestones and status

### Coding, Version Control

RStudio GitHub - coding environment, collaborative script development,
version control, merging and conflict resolution workflow, documentation
of code changes and version tracking.

### Documentation and Presentation

Quarto - Unified document format (code, analysis, interpretation) -
Integration of R code and results - Final report preparation (paper and
presentation) - Consistent style and format across deliverables.

## Reflection on tool set effectiveness

-   Miro is a great tool for visualization and brainstorming. With
    downside that it can be information-intensive for new users.
-   RStudio code collaboration with a GitHub repository has its learning
    curve. It was challenging for the first 2 weeks for us to get used
    to save, commit, push and pull. But in the end, after getting used
    to it, we think it is a great tool for R collaboration in team.
    Although it does not allow to work at the same document at the same
    time.
-   Recommendations for future projects: collaboration tool like
    Rstudio-Git and team structure take time to form. For short
    projects, it takes time to getting used to them. However, we are
    happy that we tried out these tools: It gave us a chance to learn
    some essential and popular options in the data science world.
