---
editor: 
  markdown: 
    wrap: 72
---

# Introduction

## About the authors

This is the project report by Dongyuan Gao and Daniel Huber, master
students at the HSLU University, in the module "Time Series Analysis in
Finance" in spring 2025.

## Contextual Background

Monetary policy in Switzerland is under the management of the Swiss
National Bank (SNB). Its main objective is to maintain price stability
by controlling inflation in Switzerland. During the recent history,
Switzerland has maintained a low and stable inflation rate, "from 1960
to 2024, the average inflation rate was 2.4% per year. Overall, the
price increase was 346.12%. For 2024, an inflation rate of 1.3% was
calculated"\[Infl00\].

## Problem Statement

Our team was eager to understand the efficacy of SNB's monetary policy
on inflation in Switzerland: does it significantly influence the
inflation development or vice versa? If so, we would like to determine
if changes in one can predict the other. These are engaging questions
for us, especially in recent economic environment of uncertainty. We aim
to provide solid analysis and perspectives for researchers and financial
professionals.
